//
//  Constants.swift
//  Orum
//
//  Created by 차차 on 11/5/23.
//

import Foundation

struct Constants {
    struct Lesson {
        static let system: String = "System of Hangul"
        
        static let consonant0: String = "Consonant 0" // Consonant Prologue
        static let consonant1: String = "Consonant 1" // ㄱ,ㄴ,ㄷ,ㄹ
        static let consonant2: String = "Consonant 2" // ㅁ,ㅂ,ㅅ,ㅇ,ㅈ
        static let consonant3: String = "Consonant 3" // ㅊ,ㅋ,ㅌ,ㅍ,ㅎ
        static let consonant4: String = "Consonant 4" // ㄲ,ㄸ,ㅃ,ㅆ,ㅉ
        static let consonant5: String = "Consonant 5" // Consonant Quiz
        
        static let vowel0: String = "Vowel 0" // Vowel Prologue
        static let vowel1: String = "Vowel 1" // ㅡ,ㅣ : ㅏ,ㅓ,ㅗ,ㅜ : ㅐ,ㅔ
        static let vowel2: String = "Vowel 2" // ㅑ,ㅕ,ㅛ,ㅠ,ㅒ,ㅖ
        static let vowel3: String = "Vowel 3" // ㅢ,ㅟ,ㅚ,ㅘ,ㅝ,ㅙ,ㅞ
        static let vowel4: String = "Vowel 4" // Vowel Quiz
        
        static let batchim0: String = "Batchim 0" // Batchim Prologue
        static let batchim1: String = "Batchim 1" // ㄱ,ㄴ,ㄷ,ㄹ,ㅁ,ㅂ,ㅇ
        static let batchim2: String = "Batchim 2" // ㅅ,ㅈ,ㅊ,ㅋ,ㅌ,ㅍ,ㄲ,ㅆ
        static let batchim3: String = "Batchim 3" // ㅎ | 겹받침
        static let batchim4: String = "Batchim 4" // Batchim Epilogue

        
        static let lessons: [String] = [
            system, // 0
            consonant0, // 1
            consonant1, // 2
            consonant2, // 3
            consonant3, // 4
            consonant4, // 5
            consonant5, // 6
            vowel0, // 7
            vowel1, // 8
            vowel2, // 9
            vowel3, // 10
            vowel4, // 11
            batchim0, // 12
            batchim1, // 13
            batchim2, // 14
            batchim3, // 15
            batchim4,
        ]
        
        static let lessonComponent: [String: [String]] = [
            Constants.Lesson.system : ["System of Hangul"],
            Constants.Lesson.consonant0 : ["Prologue"],
            Constants.Lesson.consonant1 : ["ㄱ","ㄴ","ㄷ","ㄹ"],
            Constants.Lesson.consonant2 : ["ㅁ","ㅂ","ㅅ","ㅇ","ㅈ"],
            Constants.Lesson.consonant3 : ["ㅊ","ㅋ","ㅌ","ㅍ","ㅎ"],
            Constants.Lesson.consonant4 : ["ㄲ","ㄸ","ㅃ","ㅆ","ㅉ"],
            Constants.Lesson.consonant5 : ["Epilogue"],
            Constants.Lesson.vowel0 : ["Prologue"],
            Constants.Lesson.vowel1 : ["ㅡ","ㅣ","ㅏ","ㅓ","ㅗ","ㅜ","ㅐ","ㅔ"],
            Constants.Lesson.vowel2 : ["ㅑ","ㅕ","ㅛ","ㅠ","ㅒ","ㅖ"],
            Constants.Lesson.vowel3 : ["ㅢ","ㅚ","ㅟ","ㅘ","ㅝ","ㅙ","ㅞ"],
            Constants.Lesson.vowel4 : ["Epilogue"],
            Constants.Lesson.batchim0 : ["Prologue"],
            Constants.Lesson.batchim1: ["ㄱ","ㄴ","ㄷ","ㄹ","ㅁ","ㅂ","ㅇ"],
            Constants.Lesson.batchim2: ["ㅋ","ㅌ","ㄲ","ㅅ","ㅈ","ㅊ","ㅆ"],
            Constants.Lesson.batchim3 : ["ㅎ"],
            Constants.Lesson.batchim4: ["Epilogue"],
        ]
        
        static let instructionText : [String : String] = [
            Constants.Lesson.consonant1 : "The simplest consonants with the fewest strokes",
            Constants.Lesson.consonant2 : "Consonants with balanced forms",
            Constants.Lesson.consonant3 : "Consonants with high, peculiar pronunciations and complex forms",
            Constants.Lesson.consonant4 : "These consonants are doubled versions of the consonants ㄱ, ㄷ, ㅂ, ㅅ, and ㅈ that we previously learned. Their characteristic is pronouncing them with a strong emphasis.",
            Constants.Lesson.consonant5 : "Let's review the consonant we learned through a quiz.",
            Constants.Lesson.vowel1 : "We're going to learn about basic vowels that are used to make other vowels.",
            Constants.Lesson.vowel2 : "We're going to learn about vowels that are pronounced with 'ㅣ' based on basic vowels. There are two short lines for each.",
            Constants.Lesson.vowel3 : "We're going to learn about vowels that are composed of two basic vowels.",
            Constants.Lesson.vowel4 : "Let's review the vowel we learned through a quiz.",
            Constants.Lesson.batchim1: "",
            Constants.Lesson.batchim2: "When these consonants serve as batchim(final consonant), they follow pronunciation rules different from when they are initial consonants.",
            Constants.Lesson.batchim3 : "These batchim don't appear frequently and have very complex rules. Instead of memorizing them, when you encounter ㅎ or complex batchim, refer to the app for pronunciation. I'll always be here, ready to assist.",
            Constants.Lesson.batchim4: "Let's review the consonants we learned through a quiz.", // TODO: consonants -> ?
        ]
    }
    
    struct Hangul {
        static let consonants: [String] = [
            "ㄱ",
            "ㄴ",
            "ㄷ",
            "ㄹ",
            "ㅁ",
            "ㅂ",
            "ㅅ",
            "ㅇ",
            "ㅈ",
            "ㅊ",
            "ㅋ",
            "ㅌ",
            "ㅍ",
            "ㅎ",
            "ㄲ",
            "ㄸ",
            "ㅃ",
            "ㅆ",
            "ㅉ"
        ]
        
        static let consonantExamples: [String : [String]] = [
            "ㄱ" : ["가","구"],
            "ㄴ" : ["나","누"],
            "ㄷ" : ["다","두"],
            "ㄹ" : ["라","루"],
            "ㅁ" : ["마","무"],
            "ㅂ" : ["바","부"],
            "ㅅ" : ["사","수"],
            "ㅇ" : ["아","우"],
            "ㅈ" : ["자","주"],
            "ㅊ" : ["차","추"],
            "ㅋ" : ["카","쿠"],
            "ㅌ" : ["타","투"],
            "ㅍ" : ["파","푸"],
            "ㅎ" : ["하","후"],
            "ㄲ" : ["까", "꾸"],
            "ㄸ" : ["따", "뚜"],
            "ㅃ" : ["빠", "뿌"],
            "ㅆ" : ["싸", "쑤"],
            "ㅉ" : ["짜", "쭈"],
        ]
        
        static let consonantQuiz : [String : [String]] = [
            "ㄱ" : ["가로수길", "강남구"],
            "ㄴ" : ["바나나맛 우유", "누나"],
            "ㄷ" : ["다크나이트", "두부"],
            "ㄹ" : ["배스킨 라빈스", "후루트링"],
            "ㅁ" : ["마요네즈", "무지개"],
            "ㅂ" : ["보석바", "부산행"],
            "ㅅ" : ["사랑해", "수퍼마켙"],
            "ㅇ" : ["아이스크림", "새우깡"],
            "ㅈ" : ["자유시간", "제주도"],
            "ㅊ" : ["녹차", "추억"],
            "ㅋ" : ["카페", "초코칩쿠키"],
            "ㅌ" : ["스타벅스", "투게더"],
            "ㅍ" : ["초코파이", "콘푸로스트"],
            "ㅎ" : ["하트", "후참잘"],
            "ㄲ" : ["돈까스", "꿈꾸는"],
            "ㄸ" : ["아리따움", "뚜레쥬르"],
            "ㅃ" : ["아빠", "뿌링클"],
            "ㅆ" : ["싸이", "싸움의 고수"],
            "ㅉ" : ["짜파게티", "쭈꾸미"],
        ]
        
        static let consonantSound : [String : String] = [
            "ㄱ" : "g",
            "ㄴ" : "n",
            "ㄷ" : "d",
            "ㄹ" : "r",
            "ㅁ" : "m",
            "ㅂ" : "b",
            "ㅅ" : "s",
            "ㅇ" : " ",
            "ㅈ" : "j",
            "ㅊ" : "ch",
            "ㅋ" : "k",
            "ㅌ" : "t",
            "ㅍ" : "p",
            "ㅎ" : "h",
            "ㄲ" : "gg",
            "ㄸ" : "tt",
            "ㅃ" : "bb",
            "ㅆ" : "ss",
            "ㅉ" : "jj",
        ]
        
        static let consonantExamplesSound: [String : [String]] = [
            "ㄱ" : ["ga","gu"],
            "ㄴ" : ["na","nu"],
            "ㄷ" : ["da","du"],
            "ㄹ" : ["ra","ru"],
            "ㅁ" : ["ma","mu"],
            "ㅂ" : ["ba","bu"],
            "ㅅ" : ["sa","su"],
            "ㅇ" : [" a"," u"],
            "ㅈ" : ["ja","ju"],
            "ㅊ" : ["cha","chu"],
            "ㅋ" : ["ka","ku"],
            "ㅌ" : ["ta","tu"],
            "ㅍ" : ["pa","pu"],
            "ㅎ" : ["ha","hu"],
            "ㄲ" : ["gga", "ggu"],
            "ㄸ" : ["tta", "ttu"],
            "ㅃ" : ["bba", "bbu"],
            "ㅆ" : ["ssa", "ssu"],
            "ㅉ" : ["jja", "jju"],
        ]
        
        static let lottieName : [String: String] = [
            "ㄱ" : "gun",
            "ㄴ" : "nose",
            "ㄷ" : "drink",
            "ㄹ" : "road",
            "ㅁ" : "mouth",
            "ㅂ" : "bucket",
            "ㅅ" : "squid",
            "ㅇ" : "nothing",
            "ㅈ" : "jump",
            "ㅊ" : "champion",
            "ㅋ" : "key",
            "ㅌ" : "tooth",
            "ㅍ" : "pillar",
            "ㅎ" : "hat",
        ]
        
        static let consonantCombination : [String: String] = [
            "ㄲ" : "ㄱ",
            "ㄸ" : "ㄷ",
            "ㅃ" : "ㅂ",
            "ㅆ" : "ㅅ",
            "ㅉ" : "ㅈ",
        ]
        
        static let vowels: [String] = [
            "ㅡ",
            "ㅣ",
            "ㅏ",
            "ㅓ",
            "ㅗ",
            "ㅜ",
            "ㅐ",
            "ㅔ",
            "ㅑ",
            "ㅕ",
            "ㅛ",
            "ㅠ",
            "ㅒ",
            "ㅖ",
            "ㅢ",
            "ㅟ",
            "ㅚ",
            "ㅘ",
            "ㅝ",
            "ㅙ",
            "ㅞ",
        ]
        
        static let vowelExamples: [String : [String]] = [
            "ㅡ" : ["그","느"],
            "ㅣ" : ["기","니"],
            "ㅏ" : ["가","나"],
            "ㅓ" : ["거","너"],
            "ㅗ" : ["고","노"],
            "ㅜ" : ["구","누"],
            "ㅐ" : ["개","내"],
            "ㅔ" : ["게","네"],
            "ㅑ" : ["갸","냐"],
            "ㅕ" : ["겨","녀"],
            "ㅛ" : ["교","뇨"],
            "ㅠ" : ["규","뉴"],
            "ㅒ" : ["걔","냬"],
            "ㅖ" : ["계","녜"],
            "ㅢ" : ["긔", "늬"],
            "ㅟ" : ["귀", "뉘"],
            "ㅚ" : ["괴", "뇌"],
            "ㅘ" : ["과", "놔"],
            "ㅝ" : ["궈", "눠"],
            "ㅙ" : ["괘", "놰"],
            "ㅞ" : ["궤", "눼"],
        ]
        
        static let vowelStrokeCount: [String : Int] = [
            "ㅡ" : 1,
            "ㅣ" : 1,
            "ㅏ" : 2,
            "ㅓ" : 2,
            "ㅗ" : 2,
            "ㅜ" : 2,
            "ㅐ" : 3,
            "ㅔ" : 3,
            "ㅑ" : 3,
            "ㅕ" : 3,
            "ㅛ" : 3,
            "ㅠ" : 3,
            "ㅒ" : 4,
            "ㅖ" : 4,
            "ㅢ" : 2,
            "ㅟ" : 3,
            "ㅚ" : 3,
            "ㅘ" : 4,
            "ㅝ" : 4,
            "ㅙ" : 5,
            "ㅞ" : 5,
        ]
        
        static let vowelSound : [String : String] = [
            "ㅡ" : "eu",
            "ㅣ" : "i",
            "ㅏ" : "a",
            "ㅓ" : "eo",
            "ㅗ" : "o",
            "ㅜ" : "u",
            "ㅐ" : "ae",
            "ㅔ" : "ae",
            "ㅑ" : "ya",
            "ㅕ" : "yeo",
            "ㅛ" : "yo",
            "ㅠ" : "yu",
            "ㅒ" : "yae",
            "ㅖ" : "yae",
            "ㅢ" : "eui",
            "ㅟ" : "wui",
            "ㅚ" : "wea",
            "ㅘ" : "wa",
            "ㅝ" : "wue",
            "ㅙ" : "wea",
            "ㅞ" : "wea",
        ]
        
        static let vowelSimilarSound : [String : String] = [
            "ㅡ" : "Good",
            "ㅣ" : "Tree",
            "ㅏ" : "Father",
            "ㅓ" : "Cup",
            "ㅗ" : "Home",
            "ㅜ" : "Moon",
            "ㅐ" : "Face",
            "ㅔ" : "Face",
        ]
        
        static let vowelCombination : [String : String] = [
            "ㅑ" : "ㅣ[ee]\n+\nㅏ[a]",
            "ㅕ" : "ㅣ[ee]\n+\nㅓ[eo]",
            "ㅛ" : "ㅣ[ee]\n+\nㅗ[o]",
            "ㅠ" : "ㅣ[ee]\n+\nㅜ[u]",
            "ㅒ" : "ㅣ[ee]\n+\nㅐ[ae]",
            "ㅖ" : "ㅣ[ee]\n+\nㅔ[ae]",
            "ㅢ" : "ㅡ[eu]\n+\nㅣ[ee]",
            "ㅚ" : "ㅗ[o]\n+\nㅣ[ee]",
            "ㅘ" : "ㅗ[o]\n+\nㅏ[a]",
            "ㅙ" : "ㅗ[o]\n+\nㅐ[ae]",
            "ㅟ" : "ㅜ[u]\n+\nㅣ[ee]",
            "ㅝ" : "ㅜ[u]\n+\nㅓ[eo]",
            "ㅞ" : "ㅜ[u]\n+\nㅔ[ae]",
        ]
        
        static let vowelQuiz: [String : [String]] = [
            "ㅡ" : ["셀프","버스"],
            "ㅣ" : ["이태원","갈비"],
            "ㅏ" : ["타는 곳","교통카드"],
            "ㅓ" : ["서울","붕어빵"],
            "ㅗ" : ["노래방","소주"],
            "ㅜ" : ["금연구역","맥주"],
            "ㅐ" : ["대한민국","홍대입구"],
            "ㅔ" : ["인생네컷","당기세요"],
            "ㅑ" : ["야구","뭐하냐"],
            "ㅕ" : ["여기어때","겨울"],
            "ㅛ" : ["비요뜨","안녕하세요"],
            "ㅠ" : ["씨유","뉴진스"],
            "ㅒ" : ["얘들아","쟤"],
            "ㅖ" : ["예쁜","예 "],
            "ㅢ" : ["배달의 민족","여의도"],
            "ㅟ" : ["다람쥐","뷔"],
            "ㅚ" : ["외국인","육회"],
            "ㅘ" : ["화장실","와"],
            "ㅝ" : ["귀여워","뭐"],
            "ㅙ" : ["쉐이크","웨하스"],
            "ㅞ" : ["왜 ","돼지고기"],
        ]
        
        static let batchim: [String] = [
            "ㄱb",
            "ㄴb",
            "ㄷb",
            "ㄹb",
            "ㅁb",
            "ㅂb",
            "ㅅb",
            "ㅇb",
            "ㅈb",
            "ㅊb",
            "ㅋb",
            "ㅌb",
            "ㅍb",
            "ㄲb",
            "ㅆb",
        ]
                
        static let batchimSound: [String : String] = [
            "ㄱb" : "g",
            "ㄴb" : "n",
            "ㄷb" : "d",
            "ㄹb" : "r",
            "ㅁb" : "m",
            "ㅂb" : "b",
            "ㅅb" : "d",
            "ㅇb" : "ng",
            "ㅈb" : "d",
            "ㅊb" : "d",
            "ㅋb" : "g",
            "ㅌb" : "d",
            "ㅍb" : "b",
            "ㅎb" : "",
            "ㄲb" : "g",
            "ㅆb" : "d",
        ]
        
        static let batchimEndingRule : [String : String] = [
            "ㄱb" : "ㄱ",
            "ㄴb" : "ㄴ",
            "ㄷb" : "ㄷ",
            "ㄹb" : "ㄹ",
            "ㅁb" : "ㅁ",
            "ㅂb" : "ㅂ",
            "ㅅb" : "ㄷ",
            "ㅇb" : "ㅇ",
            "ㅈb" : "ㄷ",
            "ㅊb" : "ㄷ",
            "ㅋb" : "ㄱ",
            "ㅌb" : "ㄷ",
            "ㅍb" : "ㅂ",
            "ㅎb" : "",
            "ㄲb" : "ㄱ",
            "ㅆb" : "ㄷ",
        ]
        
        
        static let batchimCardCount : [String : [Int]] = [
            "Batchim 1" : [6, 1],
            "Batchim 2" : [4, 4],
        ]
        
        static let batchimTitle : [String : [String]] = [
            "Batchim 1" : ["Simplification", "Touch the Cards"],
            "Batchim 2" : ["Transformation", "Transformation"],
        ]
        
        static let batchimExplainTitle : [String : [String]] = [
            "Batchim 1" : ["Principle", "ㅇ got sound"],
            "Batchim 2" : ["ㅋ, ㄲ, ㅌ, ㅍ", "ㅅ, ㅆ, ㅈ, ㅊ"],
        ]
        
        static let batchimExplain : [String : [String]] = [
            "Batchim 1" : ["For final consonant sounds, only the 7 consonants 'ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅇ' are pronounced", "In the final position, ㅇ creates a sound"],
            "Batchim 2" : ["These are change to ㄱ, ㄷ, ㅂ respectively when used as final consonants", "Consonants containing ㅅ, namely ㅅ, ㅆ, ㅈ, and ㅊ, all transform into ㄷ when used as final consonants"],
        ]
    }
    
    struct HangulQuiz{
        
        static let options: [String : [String]] = [
            "가로수길" : ["가0", "가1", "가2"],
            "강남구" : ["구0", "구1", "구2"],
            "바나나맛 우유" : ["나0", "나1", "나2"],
            "누나" : ["누0", "누1", "누2"],
            "다크나이트" : ["다1", "다2", "다3"],
            "두부" : ["두0","두1","두2"],
            "배스킨 라빈스" : ["라0","라1","라2"],
            "후루트링" : ["루0","루1","루2"],
            "마요네즈" : ["마0","마1","마2"],
            "무지개" : ["무0","무1","무2"],
            "보석바" : ["바0","바1","바2"],
            "부산행" : ["부0","부1","부2"],
            "사랑해" : ["사0","사1","사2"],
            "수퍼마켙" : ["수0","수1","수2"],
            "아이스크림" : ["아0","아1","아2"],
            "새우깡" : ["우0","우1","우2"],
            "자유시간" : ["자0","자1","자2"],
            "제주도" : ["주0","주1","주2"],
            "녹차" : ["차0","차1","차2"],
            "추억" : ["추0","추1","추2"],
            "카페" : ["카0","카1","카2"],
            "초코칩쿠키" : ["쿠0","쿠1","쿠2"],
            "스타벅스" : ["타0","타1","타2"],
            "투게더" : ["투0","투1","투2"],
            "초코파이" : ["파0","파1","파2"],
            "콘푸로스트" : ["푸0","푸1","푸2"],
            "하트" : ["하0","하1","하2"],
            "후참잘" : ["후0","후1","후2"],
            "돈까스" : ["까1","까2","까3"],
            "꿈꾸는" : ["꾸0","꾸1","꾸2"],
            "아리따움" : ["따0","따1","따2"],
            "뚜레쥬르" : ["뚜0","뚜1","뚜2"],
            "아빠" : ["빠0","빠1","빠2"],
            "뿌링클" : ["뿌0","뿌1","뿌2"],
            "싸이" : ["싸0","싸1","싸2"],
            "싸움의 고수" : ["쑤0","쑤1","쑤2"],
            "짜파게티" : ["짜0","짜1","짜2"],
            "쭈꾸미" : ["쭈0","쭈1","쭈2"],
            "셀프" : ["ㅡ0","ㅡ1","ㅡ2"],
            "버스" : ["ㅡ3","ㅡ4","ㅡ5"],
            "이태원" : ["ㅣ0","ㅣ1","ㅣ2"],
            "갈비" : ["ㅣ3","ㅣ4","ㅣ5"],
            "타는 곳" : ["ㅏ0","ㅏ1","ㅏ2"],
            "교통카드" : ["ㅏ3","ㅏ4","ㅏ5"],
            "서울" : ["ㅓ0","ㅓ1","ㅓ2"],
            "붕어빵" : ["ㅓ3","ㅓ4","ㅓ5"],
            "노래방" : ["ㅗ0","ㅗ1","ㅗ2"],
            "소주" : ["ㅗ3","ㅗ4","ㅗ5"],
            "금연구역" : ["ㅜ0","ㅜ1","ㅜ2"],
            "맥주" : ["ㅜ3","ㅜ4","ㅜ5"],
            "대한민국" : ["ㅐ0","ㅐ1","ㅐ2"],
            "홍대입구" : ["ㅐ3","ㅐ4","ㅐ5"],
            "인생네컷" : ["ㅔ0","ㅔ1","ㅔ2"],
            "당기세요" : ["ㅔ3","ㅔ4","ㅔ5"],
            "야구" : ["ㅑ0","ㅑ1","ㅑ2"],
            "뭐하냐" : ["ㅑ3","ㅑ4","ㅑ5"],
            "여기어때" : ["ㅕ0","ㅕ1","ㅕ2"],
            "겨울" : ["ㅕ3","ㅕ4","ㅕ5"],
            "비요뜨" : ["ㅛ0","ㅛ1","ㅛ2"],
            "안녕하세요" : ["ㅛ3","ㅛ4","ㅛ5"],
            "씨유" : ["ㅠ0","ㅠ1","ㅠ2"],
            "뉴진스" : ["ㅠ3","ㅠ4","ㅍ5"],
            "얘들아" : ["ㅒ0","ㅒ1","ㅒ2"],
            "쟤" : ["ㅒ3","ㅒ4","ㅒ5"],
            "예쁜" : ["ㅖ0","ㅖ1","ㅖ2"],
            "예" : ["ㅖ3","ㅖ4","ㅖ5"],
            "배달의 민족" : ["ㅢ0","ㅢ1","ㅢ2"],
            "여의도" : ["ㅢ3","ㅢ4","ㅢ5"],
            "다람쥐" : ["ㅟ0","ㅟ1","ㅟ2"],
            "뷔" : ["ㅟ3","ㅟ4","ㅟ5"],
            "외국인" : ["ㅚ0","ㅚ1","ㅚ2"],
            "육회" : ["ㅚ3","ㅚ4","ㅚ5"],
            "화장실" : ["ㅘ0","ㅘ1","ㅘ2"],
            "와" : ["ㅘ3","ㅘ4","ㅘ5"],
            "귀여워" : ["ㅝ0","ㅝ1","ㅝ2"],
            "뭐" : ["ㅝ3","ㅝ4","ㅝ5"],
            "쉐이크" : ["ㅞ0","ㅞ1","ㅞ2"],
            "웨하스" : ["ㅞ3","ㅞ4","ㅞ5"],
            "왜" : ["ㅙ0","ㅙ1","ㅙ2"],
            "돼지고기" : ["ㅙ3","ㅙ4","ㅙ5"]
        ]
        
        static let meaning: [String : String] =  [
            "가로수길" : "Garosu-gil",
            "강남구":"Gangnam-district",
            "바나나맛 우유":"Banana flavor milk",
            "누나":"Sister",
            "다크나이트":"Dark Knight(Film)",
            "두부":"Tofu",
            "배스킨 라빈스":"Baskin Robbins",
            "후루트링":"Fruit Ring",
            "마요네즈":"Mayonnaise",
            "무지개":"Rainbow",
            "보석바":"Jewelry bar(Ice cream)",
            "부산행":"Train to busan",
            "사랑해":"Love you",
            "수퍼마켙":"Supermarket",
            "아이스크림":"Ice cream",
            "새우깡":"Shrimp snack",
            "자유시간":"Free time(Chocolate bar)",
            "제주도":"Jeju island",
            "녹차":"Green tea",
            "추억":"Memory",
            "카페":"Cafe",
            "초코칩쿠키":"Chocolate chip cookie",
            "스타벅스":"Starbucks",
            "투게더":"Together(Ice cream)",
            "초코파이":"Chocolate pie",
            "콘푸로스트":"Corn frost(Frosted Flakes)",
            "하트":"Heart",
            "후참잘":"Fuchamjal(Fried chicken restaurant)",
            "돈까스":"Pork cutlet",
            "꿈꾸는":"Dreaming",
            "아리따움":"ARITAUM(Cosmetic shop)",
            "뚜레쥬르":"Tous les Jours(Bakery)",
            "아빠":"Father",
            "뿌링클":"Bburinkle(Menu of Fried chicken restaurant)",
            "싸이":"Psy",
            "싸움의 고수":"Fighting",
            "짜파게티":"Jjapagetti(Instant Chajangmyun Noodles)",
            "쭈꾸미":"Small octopus",
            "셀프":"Self",
            "버스":"Bus",
            "이태원":"Itaewon",
            "갈비":"Galbi",
            "타는 곳":"Place to ride",
            "교통카드":"Transportaton Card",
            "서울":"Seoul",
            "붕어빵":"Fish-shaped bun(Street food)",
            "노래방":"Karaoke",
            "소주":"Soju",
            "금연구역":"Non-smoking area",
            "맥주":"Beer",
            "대한민국":"Korea",
            "홍대입구":"Hongik University(Subway station)",
            "인생네컷":"Life's four cuts(Instant photo booth)",
            "당기세요":"Pull",
            "야구":"Baseball",
            "뭐하냐":"What are you doing?",
            "여기어때":"How about here?(Korean Airbnb)",
            "겨울":"Winter",
            "비요뜨":"Viyott",
            "안녕하세요":"Hello",
            "씨유":"CU(Convenience store)",
            "뉴진스":"NewJeans",
            "얘들아":"You guys",
            "쟤":"He or She(That person)",
            "에쁜":"Pretty",
            "예":"Yes",
            "배달의 민족":"Nation of delivery(Korean Uber)",
            "여의도":"Yeouido(Large island on the Han River)",
            "다람쥐":"Chipmunk",
            "뷔":"V(BTS)",
            "외국인":"Foreigner",
            "육회":"Beef Tartare",
            "화장실":"Toilet",
            "와":"Wow(ice cream)",
            "귀여워":"Cute",
            "뭐":"What",
            "쉐이크":"Shake",
            "웨하스":"Wafers",
            "왜":"Why",
            "돼지고기":"Pork"
        ]
        
        static let tmi : [String : String] = [
            "가로수길" : "used to be the hottest street in Korea, but not anymore",
            "강남구":"",
            "바나나맛 우유":"",
            "누나":"",
            "다크나이트":"",
            "두부":"",
            "배스킨 라빈스":"",
            "후루트링":"",
            "마요네즈":"",
            "무지개":"",
            "보석바":"",
            "부산행":"",
            "사랑해":"",
            "수퍼마켙":"",
            "아이스크림":"",
            "새우깡":"",
            "자유시간":"",
            "제주도":"",
            "녹차":"",
            "추억":"",
            "카페":"",
            "초코칩쿠키":"",
            "스타벅스":"",
            "투게더":"",
            "초코파이":"",
            "콘푸로스트":"",
            "하트":"",
            "후참잘":"",
            "돈까스":"",
            "꿈꾸는":"",
            "아리따움":"",
            "뚜레쥬르":"",
            "아빠":"",
            "뿌링클":"",
            "싸이":"",
            "싸움의 고수":"",
            "짜파게티":"",
            "쭈꾸미":"",
            "셀프":"",
            "버스":"",
            "이태원":"",
            "갈비":"",
            "타는 곳":"",
            "교통카드":"",
            "서울":"",
            "붕어빵":"",
            "노래방":"",
            "소주":"",
            "금연구역":"",
            "맥주":"",
            "대한민국":"",
            "홍대입구":"",
            "인생네컷":"",
            "당기세요":"",
            "야구":"",
            "뭐하냐":"",
            "여기어때":"",
            "겨울":"",
            "비요뜨":"",
            "안녕하세요":"",
            "씨유":"",
            "뉴진스":"",
            "얘들아":"",
            "쟤":"",
            "에쁜":"",
            "예":"",
            "배달의 민족":"",
            "여의도":"",
            "다람쥐":"",
            "뷔":"",
            "외국인":"",
            "육회":"",
            "화장실":"",
            "와":"",
            "귀여워":"",
            "뭐":"",
            "쉐이크":"",
            "웨하스":"",
            "왜":"",
            "돼지고기":""
        ]
    }
    
    struct Practice{
        
        static let chapter : [String] = [
            "Food",
            "Tourism",
            "Daily Life"
        ]
        
        static let thumbnail : [String : String] = [
            "Food" : "Practice 0",
            "Tourism" : "Practice 1",
            "Daily Life" : "Practice 2"
        ]
        
        static let word : [String : [String]] = [
            "Food" : ["국밥", "치맥", "삼겹살", "불고기", "삼계탕", "칼국수", "닭한마리", "라면", "불닭볶음면", "김밥", "김치", "육회", "떡볶이", "소주", "빈대떡", "냉면", "비빔밥","붕어빵"],
            "Tourism" : ["홍대", "성수", "서울", "강남", "인천", "부산", "한강", "익선동", "이태원", "동대문", "혜화", "종로", "광장시장", "지하철", "버스", "가로수길", "인천국제공항", "경복궁", "남산", "명동"],
            "Daily Life" : ["안녕하세요", "감사합니다", "죄송합니다", "맛있어요", "~ 주세요", "~ 어디에요", "얼마에요", "도와주세요", "편의점", "병원", "화장실", "좋아요", "싫어요", "네", "아니요"]
        ]
        
        static let image : [String : String] = [
            "국밥" : "gukbap",
            "치맥" : "chimac",
            "삼겹살" : "samgyeopsal",
            "불고기" : "bulgogi",
            "삼계탕" : "samgyetang",
            "칼국수" : "kalguksu",
            "닭한마리" : "dakanmari",
            "라면" : "ramyun",
            "불닭볶음면" : "buldak",
            "김밥" : "gimbap",
            "김치" : "kimchi",
            "육회" : "yukhoe",
            "떡볶이" : "tteokbokki",
            "소주" : "soju",
            "빈대떡" : "bindaedduk",
            "냉면" : "naengmyun",
            "비빔밥" : "bibimbap",
            "붕어빵" : "fish-shaped bun",
            "홍대" : "hongdae",
            "성수" : "sungsu",
            "서울" : "seoul",
            "강남" : "gangnam",
            "인천" : "incheon",
            "부산" : "busan",
            "한강" : "hangang",
            "익선동" : "iksundong",
            "이태원" : "itaewon",
            "동대문" : "dongdaemun",
            "혜화" : "hyehwa",
            "종로" : "jongro",
            "광장시장" : "gwangjangsijang",
            "지하철" : "jihachul",
            "버스" : "bus",
            "가로수길" : "garosugil",
            "인천국제공항" : "airport",
            "경복궁" : "gyeongbokgung",
            "남산" : "namsan",
            "명동" : "myeongdong",
            "안녕하세요" : "hi",
            "감사합니다" : "thankyou",
            "죄송합니다" : "sorry",
            "맛있어요" : "delicious",
            "~ 주세요" : "giveme",
            "~ 어디에요" : "where",
            "얼마에요" :  "howmuch",
            "도와주세요" : "helpme",
            "편의점" : "conveniencestore",
            "병원" : "hospital",
            "화장실" : "toilet",
            "좋아요" : "like",
            "싫어요" : "hate",
            "네" : "yes",
            "아니요" : "no",
        ]
        
        static let explanation : [String : String] = [
            "국밥" : "국밥 is a tasty Korean dish with soup and rice. Imagine a rich soup with meat and veggies poured over rice—it's cozy and delicious, a classic in Korean food!",
            "치맥" : "치맥 is a popular food combo in Korea, where you enjoy '치킨' (chicken) and '맥주' (beer) together. It's something Koreans often do during get-togethers or with friends. It's all about having a good time with delicious chicken and cold beer!",
            "삼겹살" : "Pork belly, known as '삼겹살' in Korea, is a popular dish where thin slices of pork belly are grilled, usually at the table. It's tender and delicious, a dish that families and friends in Korea enjoy together!",
            "불고기" : "불고기 is a popular Korean dish where thinly sliced beef is marinated in a sweet and savory sauce and then grilled. It has a unique and delicious flavor, often enjoyed in a barbecue style, but it's also easy to make at home.",
            "삼계탕" : "삼계탕 is a traditional Korean dish, especially popular in the summer. It's like a healthy soup made with chicken, ginseng, and some rice. People love it because it's tasty, and they believe it helps boost energy and keep them healthy.",
            "칼국수" : "칼국수 is a type of Korean noodle dish featuring thin, flat noodles. These noodles are hand-pulled and cooked in a boiling broth. It's often served with either chicken or beef broth, and it has a light and refreshing taste. It's especially popular to enjoy on chilly days in Korea!",
            "닭한마리" : "닭한마리 is a Seoul-style cuisine where chicken pieces, boiled in broth with green onions, onions, and other ingredients, are simmered with black pepper, spices, garlic, ginger, and more in a hot pot. It is more famous among foreigners than Koreans.",
            "라면" : "라면 is a popular and easy-to-make noodle dish from Korea. It involves boiling noodles and mixing them with soup. There are various flavors and types, making it a favorite among many. It's well-known for being a quick and tasty meal!",
            "불닭볶음면" : "불닭볶음면, also known as 'Spicy Fire Chicken Noodles,' is a spicy chicken 라면. It's a popular choice among those who enjoy spicy foods in Korea!",
            "김밥" : "삼각김밥, also known as 'Triangle Kimbap,' is a simple triangular-shaped rice roll. Inside, you'll find a variety of ingredients such as rice, egg, tuna, and vegetables. It's a convenient and popular snack enjoyed at schools or workplaces.",
            "김치" : "김치 is a traditional Korean dish, made by fermenting vegetables like cabbage or radishes with gochujang (red chili paste). It has a spicy flavor and is often enjoyed with rice or used in various dishes. It plays a significant role in Korean culinary culture.",
            "육회" : "육회 is a Korean dish made with raw beef that is fresh and seasoned. Typically, the beef is finely chopped and mixed with a seasoning sauce containing soy sauce, sugar, sesame oil, and other ingredients. It has a tender texture and a rich, savory flavor. It's often enjoyed on special occasions or gatherings in Korea.",
            "떡볶이" : "떡볶이 is a popular Korean snack made with chewy rice cakes in a sweet and spicy gochujang (red chili paste) sauce With every bite, you get a delightful mix of sweet and spicy flavors. It's a beloved street food and commonly enjoyed at snack stalls or casual eateries in Korea.",
            "소주" : "소주 is a traditional Korean spirit and a popular alcoholic beverage. It' offering a clean and slightly fruity taste with a distinctive aroma. Known for its clarity, soju is versatile and commonly enjoyed in social gatherings or work-related outings in Korea.",
            "빈대떡" : "빈대떡 made by blending sweet potatoes and potatoes into a doug. The dough is then shaped into round pancakes. It has a soft, chewy texture and a sweet flavor. In Korea, it's commonly enjoyed as a homemade snack or can be found in stores, where it's grilled and sold.",
            "냉면" : "냉면 is a representative dish in Korea during the summer season. It consists of chilled soup, chewy noodles, and various toppings. Typically, it includes thinly sliced brisket, fresh vegetables, a boiled egg, and ice, creating a refreshing and tangy flavor. Koreans often enjoy 냉면, especially during hot and refreshing summer days.",
            "비빔밥" : "비빔밥 is a traditional Korean dish where various vegetables are mixed with rice, seasoned with sauce, and often enjoyed with added meat in contemporary versions.",
            "붕어빵" : "붕어빵 is a traditional Korean snack. It's a fish-shaped pastry filled with sweet red bean paste. Traditionally, it's cooked in a fish-shaped mold, but nowadays, you can find it in various shapes and flavors. The most common type features a sweet and soft bread exterior with a delicious sweet red bean filling. It's a popular street food in Korea and enjoyed by many.",
            "홍대" : "홍대 is a vibrant district in Seoul, known for its thriving arts and culture scene. It's a hub where many artists, designers, and musicians gather. The area is packed with unique shops, art galleries, clubs, and cafes. Particularly in the evening, 홍대 comes alive with diverse cultural events and entertainment.",
            "성수" : "성수 in Seoul used to be an industrial area filled with factories. Now, it's a trendy neighborhood known for art, design shops, and cool cafes. You can still see traces of the old factories, giving the area a unique charm.",
            "서울" : "서울 is the capital and largest city of South Korea, boasting a blend of modernity and dynamic culture alongside rich historical heritage. The city offers a unique experience with its harmonious mix of advanced urbanization and traditional Korean culture. Seoul is filled with diverse culinary options, shopping districts, and entertainment venues, while also featuring beautiful parks and historic landmarks.",
            "강남" : "강남 is a lively district in Seoul, known for its vibrant energy and upscale atmosphere. It's a area with high-end shopping, trendy cafes, and a dynamic nightlife scene. Gangnam is also famous for its modern architecture, business districts, and being a hub for entertainment and fashion. It's a place where contemporary lifestyle meets Korean pop culture, offering a diverse range of experiences for visitors.",
            "인천" : "인천 is a city in South Korea with a mix of modern and traditional vibes. It's famous for its international airport, bustling markets, and scenic coastal areas. You can enjoy delicious seafood, explore historical sites, and even take a ferry to nearby islands. 인천 offers a diverse experience, blending the old and the new, making it a great place to visit.",
            "부산" : "부산 is a lively city in South Korea known for its beautiful beaches, delicious seafood, and vibrant atmosphere. It's a coastal city with a mix of modern and traditional charm. Haeundae Beach and Gamcheon Culture Village are popular spots, offering stunning views and unique experiences.",
            "한강" : "The 한강, also known as Han river, flows through the heart of Seoul, South Korea. It's a scenic and iconic river with beautiful parks and bridges. Many people enjoy leisure activities along the riverside, such as cycling, picnicking, and taking boat cruises. 한강 is not only a natural landmark but also a popular spot for locals and visitors to relax and enjoy outdoor activities amidst the vibrant city.",
            "익선동" : "익선동 is a small neighborhood in the heart of Seoul, known for its unique shops and artistic atmosphere. The narrow streets are filled with various craft stores and charming cafes, making it a great place for a stroll. This neighborhood harmoniously blends tradition and modernity, offering a fantastic opportunity to experience Korean art and culture.",
            "이태원" : "이태원 is a vibrant district in Seoul, known for its diverse and international atmosphere. Famous for being a hub of cultural exchange, it attracts a significant number of foreigners. The neighborhood offers a mix of global cuisines, trendy boutiques, and lively nightlife, making it a popular destination for both locals and a melting pot of people from around the world.",
            "동대문" : "동대문 is a vibrant district in Seoul, known for its bustling markets and iconic shopping centers. It's a paradise for shoppers, offering a wide range of fashion items, accessories, and unique finds. The area is also famous for its lively atmosphere, especially at night when the neon lights illuminate the city. Dongdaemun is a must-visit destination for those looking to experience the excitement of shopping and the vibrant city life of Seoul.",
            "혜화" : "혜화 is a lively district in Seoul, celebrated for its vibrant cultural scene and youthful energy. It's a particularly renowned for being a hub where you can enjoy various theatrical performances, showcasing the dynamic arts and entertainment culture of Seoul. If you're into theater and want to experience the lively arts scene, 혜화 is the perfect destination for you.",
            "종로" : "종로 is a historic district in the heart of Seoul, Known for its rich cultural heritage. you'll find ancient palaces like Gyeongbokgung and Changdeokgung. The area is a mix of old and new, where historical landmarks blend seamlessly with modern shops and vibrant street markets. If you want to experience the essence of Seoul's history and culture, 종로 is the place to explore",
            "광장시장" : "광장시장 is a bustling traditional market in the heart of Seoul. It’s not only a great place to try authentic Korean street food but also to experience the lively energy of a traditional Korean market. It's a must-visit for those looking to savor local flavors and soak in the vibrant market culture.",
            "지하철" : "Korean 지하철(Subway) system is known for its efficiency and cleanliness. It's a convenient way to navigate the city with signs and announcements in both Korean and English. The stations are equipped with various facilities like rest areas, shops, and even underground malls.",
            "버스" : "At Korean 버스(Bus) stops, there are digital screens displaying upcoming bus information. These screens typically show the expected arrival time, route number, and types of buses serving the stop. They are continuously updated in real-time, providing accurate information on the current location of the bus and its estimated time of arrival.",
            "가로수길" : "가로수길 is a trendy and fashionable street in Seoul, South Korea. Lined with beautiful gingko trees, it's a popular destination for shopping, dining, and exploring unique boutiques. The street is known for its vibrant atmosphere, stylish cafes, and a mix of both local and international fashion brands. ",
            "인천국제공항" : "인천 국제 공항(Incheon International Airport) is South Korea's primary gateway, located near Seoul. Renowned for its world-class facilities and efficiency, it serves as a major hub for international travel. The airport boasts modern amenities, diverse dining options, duty-free shopping, and convenient transportation links to the city.",
            "경복궁" : "경복궁, located in the heart of Seoul is a grand and historic palace. It served as the main royal palace during the Joseon Dynasty and is renowned for its beautiful traditional architecture and expansive grounds. Visitors can explore the impressive main gate, Gwanghwamun, the iconic throne hall, Geunjeongjeon.",
            "남산" : "남산, situated in the heart of Seoul, South Korea, is a prominent mountain offering panoramic views of the city. At its summit stands N Seoul Tower, an iconic landmark and observation deck providing breathtaking vistas. The mountain is a popular destination for locals and tourists alike, offering scenic walking paths, beautiful parks, and a cable car for a convenient ascent.",
            "명동" : "명동, located in the heart of Seoul, is a vibrant and bustling shopping district that attracts locals and tourists alike. Known for its trendy fashion boutiques, beauty shops, and diverse street food stalls, 명동 offers a dynamic shopping experience. The area is also home to major international brands, making it a popular destination for fashion enthusiasts. ",
            "안녕하세요" : "Hi / Hello",
            "감사합니다" : "Thank you",
            "죄송합니다" : "I’m sorry",
            "맛있어요" : "It's delicious",
            "~ 주세요" : "Please give me ~",
            "~ 어디에요" : "Where is the ~",
            "얼마에요" :  "How much is it",
            "도와주세요" : "Help me",
            "편의점" : "Convenience Store",
            "병원" : "Hospital",
            "화장실" : "Toilet",
            "좋아요" : "Good(Like it)",
            "싫어요" : "I don’t like",
            "네" : "Yes",
            "아니요" : "No",
        ]
    }
    
    struct Prologue {
        static let title : [String : String] = [
            "onboarding0" : "Kompass",
            "onboarding1" : "Kompass is Fast",
            "onboarding2" : "Kompass is Precise",
            "onboarding3" : "Kompass is Handy",
            "onboarding4" : "Kompass is Alive",
            "system0" : "Consonants and Vowels",
            "system1" : "Letter in English and Hangul",
            "system2" : "Hangul Letter",
            "system3" : "Word",
            "consonant0" : "Hangul Consonants",
            "consonant1" : "Definition of Consonant",
            "consonant2" : "Associative Memory",
            "consonant3" : "Consonants Can't Make Sounds Alone!",
            "consonant4" : "Vowel ㅏ, ㅜ",
            "vowel0" : "Hangul Vowels",
            "vowel1" : "Definition of Vowel",
            "vowel2" : "Vowels and Consonants Are Different!",
            "vowel3" : "Let's study while writing.",
            "batchim0" : "Batchim",
            "batchim1" : "Definition of Batchim",
            "batchim2" : "There's a Batchim that changes the sound!",
            "batchim3" : "Double Batchim?",
            
        ]
        
        static let text : [String : String] = [
            "onboarding0" : "**Kompass** was created to give you **a fast and precise way** to read the Korean alphabet, ‘**Hangul**.’",
            "onboarding1" : "**Kompass** is the easiest way to help people who want to read **Hangul** quickly.",
            "onboarding2" : "It's not just about learning quickly. **Kompass** researches the most efficient methods for each part, providing easy and detailed guidance.",
            "onboarding3" : "Even if you study, it doesn't mean you can always be perfect. With **Kompass**, you can easily check Korean anytime, anywhere.",
            "onboarding4" : "At **Kompass**, you can listen to words that can be seen and heard in various environments in Korea, pronounced by Koreans themselves.",
            "system0" : "Hangul is a character that can be written **phonetically**. It consists of **consonants** and **vowels!**",
            "system1" : "A letter in English is one alphabet. But a **letter in Hangul** is a **combination of consonants and vowels!**",
            "system2" : "A **Hangul letter** is a combination of consonants and vowels, so basically the form is **'C+V'** or **'C+V+C'**!",
            "system3" : "A **Hangul word** is a combination of letters. Is it hard? \n\n Learning Hangul won't be difficult, **so give it a try!**",
            "consonant0" : "There are **19 consonants** used in Hangul.",
            "consonant1" : "Consonants are speech sounds made by **partially or completely blocking the flow of air from the mouth.**",
            "consonant2" : "Mnemonics is an effective teaching method, so Kompass will teach you consonants through **Associative Memory.**",
            "consonant3" : "**Consonants cannot make their own sounds, and it is a rule to make sounds only when combined with vowels.",
            "consonant4" : "So We'll tell you in advance the ㅏ, ㅜ of the vowels that you'll learn in the next part. so listen to the sound.",
            "vowel0" : "There are **21 vowels** used in Hangul.",
            "vowel1" : "Vowels are a speech sounds made with **mouth open** and **tongue in the middle of mouth not touching teeth, lips, etc.**",
            "vowel2" : "Consonants are located at the **beginning or end of a letter**, vowels are located at the **center.**",
            "vowel3" : "Vowels often have **similar shapes.** If you **write** it yourself, you'll naturally know everything.",
            "batchim0" : "There are **27 batchims** used in Hangul.",
            "batchim1" : "At the end of a consonant and vowel combination, **an additional consonant** may be added, called a **Batchim.**",
            "batchim2" : "Consonants sometimes have different sounds when they are placed in the **first position** and in the **Batchim position.**",
            "batchim3" : "One of the Batchims is the **Double Batchim**. This may seem difficult, but some of them are rarely used, **so read lightly.**",
        ]
        
        static let image : [String : [String] ] = [
        
            "onboarding0" : ["onboarding0"],
            "onboarding1" : ["onboarding1"],
            "onboarding2" : ["onboarding2"],
            "onboarding3" : ["onboarding3"],
            "onboarding4" : ["onboarding4"],
            "system0" : ["system0"],
            "system1" : ["system1"],
            "system2" : ["system20", "system21"],
            "system3" : ["system3"],
            "consonant0" : ["consonant0"],
            "consonant1" : ["consonant1"],
            "consonant2" : ["consonant2"],
            "consonant3" : ["consonant3"],
            "consonant4" : ["consonant4"],
            "vowel0" : ["vowel0"],
            "vowel1" : ["vowel1"],
            "vowel2" : ["vowel2"],
            "vowel3" : ["vowel3"],
            "batchim0" : ["batchim0"],
            "batchim1" : ["batchim1"],
            "batchim2" : ["batchim2"],
            "batchim3" : ["batchim3"],
            
        ]
    }
}
